export type SupervisorResult = 'PASSED' | 'FAILED';
export type DriverCategory = 'General' | 'Professional';

export interface TestLogItem {
  id: string;
  timestamp: string;
  officerName: string;
  officerServiceNo: string;
  driverName: string;
  driverId: string;
  driverCategory: DriverCategory;
  result: SupervisorResult;
  reading: number;
  location: string;
  roadblock: string;
  gps: string;
  notes: string;
  photos: string[];
  voiceNoteSummary: string;
}

export const testLogs: TestLogItem[] = [
  {
    id: 'IS-2026-0407-001',
    timestamp: '2026-04-07 06:15',
    officerName: 'Sgt. N. Dlamini',
    officerServiceNo: 'SA-TRF-1182',
    driverName: 'Mandla Khoza',
    driverId: '8506145234082',
    driverCategory: 'Professional',
    result: 'FAILED',
    reading: 0.07,
    location: 'N1 Southbound, Sandton',
    roadblock: 'Sandton Gate 3',
    gps: '-26.1070, 28.0567',
    notes: 'Subject exhibited slurred speech and delayed response to instructions. Second sample confirmed.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Audio note attached from officer bodycam, 00:47 duration.',
  },
  {
    id: 'IS-2026-0407-002',
    timestamp: '2026-04-07 06:28',
    officerName: 'Cst. T. Maseko',
    officerServiceNo: 'SA-TRF-1021',
    driverName: 'Sibongile Ndlovu',
    driverId: '9202118832089',
    driverCategory: 'General',
    result: 'PASSED',
    reading: 0.03,
    location: 'M1 Northbound, CBD',
    roadblock: 'Braamfontein East',
    gps: '-26.1932, 28.0323',
    notes: 'Driver cooperative. Documentation complete and verified.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'No additional voice note required.',
  },
  {
    id: 'IS-2026-0407-003',
    timestamp: '2026-04-07 07:03',
    officerName: 'Sgt. P. van Wyk',
    officerServiceNo: 'SA-TRF-0964',
    driverName: 'Thabo Mokoena',
    driverId: '7805026621188',
    driverCategory: 'Professional',
    result: 'FAILED',
    reading: 0.05,
    location: 'R24 Eastbound, East Rand',
    roadblock: 'OR Tambo Link',
    gps: '-26.1367, 28.2314',
    notes: 'Driver claims recent mouthwash use; second confirmatory test also above limit.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Officer voice note 01:12 with procedural checklist.',
  },
  {
    id: 'IS-2026-0407-004',
    timestamp: '2026-04-07 07:29',
    officerName: 'Cst. R. Nkomo',
    officerServiceNo: 'SA-TRF-1217',
    driverName: 'Lerato Msimang',
    driverId: '9001187732080',
    driverCategory: 'General',
    result: 'PASSED',
    reading: 0.01,
    location: 'N3 Interchange, Midrand',
    roadblock: 'Allandale Slip',
    gps: '-25.9976, 28.1264',
    notes: 'Routine stop. No visible impairment.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'No voice annotation.',
  },
  {
    id: 'IS-2026-0407-005',
    timestamp: '2026-04-07 08:11',
    officerName: 'Insp. K. Naidoo',
    officerServiceNo: 'SA-TRF-1304',
    driverName: 'Akhona Cele',
    driverId: '9409236814080',
    driverCategory: 'Professional',
    result: 'FAILED',
    reading: 0.08,
    location: 'N12 Eastbound, Eldorado Park',
    roadblock: 'Eldorado Ramp',
    gps: '-26.2719, 27.9124',
    notes: 'Commercial permit verified. Driver admitted consuming alcohol 2 hours prior.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Dashcam annotation attached, 00:36 duration.',
  },
  {
    id: 'IS-2026-0407-006',
    timestamp: '2026-04-07 09:02',
    officerName: 'Cst. L. Mokoena',
    officerServiceNo: 'SA-TRF-1149',
    driverName: 'Peter du Toit',
    driverId: '8602115043088',
    driverCategory: 'General',
    result: 'PASSED',
    reading: 0.02,
    location: 'M2 Westbound, Jeppestown',
    roadblock: 'Commissioner Split',
    gps: '-26.2071, 28.0659',
    notes: 'Routine check complete. Valid license and no signs of impairment.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'No additional voice note required.',
  },
  {
    id: 'IS-2026-0407-007',
    timestamp: '2026-04-07 09:41',
    officerName: 'Sgt. N. Dlamini',
    officerServiceNo: 'SA-TRF-1182',
    driverName: 'Brenda Nkosi',
    driverId: '9107027738082',
    driverCategory: 'General',
    result: 'FAILED',
    reading: 0.06,
    location: 'N1 Southbound, Rivonia Exit',
    roadblock: 'Sandton Gate 3',
    gps: '-26.0665, 28.0591',
    notes: 'Driver was cooperative. Referred to secondary processing desk.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Officer memo uploaded with sequence confirmation.',
  },
  {
    id: 'IS-2026-0407-008',
    timestamp: '2026-04-07 10:08',
    officerName: 'Cst. T. Maseko',
    officerServiceNo: 'SA-TRF-1021',
    driverName: 'Nkululeko Dube',
    driverId: '8912046112085',
    driverCategory: 'Professional',
    result: 'PASSED',
    reading: 0.01,
    location: 'M1 Northbound, Parktown',
    roadblock: 'Braamfontein East',
    gps: '-26.1799, 28.0361',
    notes: 'Professional driver. All docs in order.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'No voice annotation.',
  },
  {
    id: 'IS-2026-0407-009',
    timestamp: '2026-04-07 11:25',
    officerName: 'Sgt. P. van Wyk',
    officerServiceNo: 'SA-TRF-0964',
    driverName: 'Zanele Mokoena',
    driverId: '9701024231088',
    driverCategory: 'General',
    result: 'PASSED',
    reading: 0.00,
    location: 'R24 Eastbound, Isando',
    roadblock: 'OR Tambo Link',
    gps: '-26.1478, 28.1981',
    notes: 'Zero reading after two attempts due to initial insufficient sample.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Observation protocol verified in audio note 00:21.',
  },
  {
    id: 'IS-2026-0407-010',
    timestamp: '2026-04-07 12:04',
    officerName: 'Cst. R. Nkomo',
    officerServiceNo: 'SA-TRF-1217',
    driverName: 'Musa Mthethwa',
    driverId: '8003115523080',
    driverCategory: 'Professional',
    result: 'FAILED',
    reading: 0.05,
    location: 'N3 Northbound, Buccleuch',
    roadblock: 'Allandale Slip',
    gps: '-26.0319, 28.1086',
    notes: 'Professional threshold exceeded. Vehicle secured pending handover.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Bodycam note saved with witness details.',
  },
  {
    id: 'IS-2026-0407-011',
    timestamp: '2026-04-07 12:37',
    officerName: 'Insp. K. Naidoo',
    officerServiceNo: 'SA-TRF-1304',
    driverName: 'Yolanda Nene',
    driverId: '9007300452082',
    driverCategory: 'General',
    result: 'PASSED',
    reading: 0.02,
    location: 'N12 Eastbound, Reiger Park',
    roadblock: 'Eldorado Ramp',
    gps: '-26.2298, 28.1987',
    notes: 'No contraventions observed.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'No voice annotation.',
  },
  {
    id: 'IS-2026-0407-012',
    timestamp: '2026-04-07 13:19',
    officerName: 'Cst. L. Mokoena',
    officerServiceNo: 'SA-TRF-1149',
    driverName: 'Ruan Visser',
    driverId: '9508076019084',
    driverCategory: 'General',
    result: 'FAILED',
    reading: 0.07,
    location: 'M2 Westbound, Denver',
    roadblock: 'Commissioner Split',
    gps: '-26.2196, 28.0892',
    notes: 'Driver requested legal representative. Case forwarded.',
    photos: ['/maps/johannesburg-map.png', '/splash-hero.png'],
    voiceNoteSummary: 'Incident summary uploaded by field tablet.',
  },
];

const uniqueOfficers = new Set(testLogs.map((x) => x.officerServiceNo));

export const todayStats = {
  totalTests: testLogs.length,
  totalFailures: testLogs.filter((x) => x.result === 'FAILED').length,
  activeOfficers: uniqueOfficers.size,
  pendingReviews: 5,
};

